### ISSUE TITLE
please please remove the zooming problem from the home screen like the lock screen area the ratio of the home screen is changing with every pic or video the zoom disabling option in the tweak is not working properly still we see zooming action please fix it or updated with a fast release thank you for the professionally and best regards

### ISSUE THREAD

**Issue by aboulnemer** [vyolit/Eneko#21]
**Describe the requested feature:**

**System information:**
- iOS version:
- Device:
- Jailbreak:

**Comment by vyolit** [comment]
There is an option to disable the zoom. Open your eyes.

**Comment by aboulnemer** [comment]
dear no offense at all' you can see still a small zooming effect even if you disabling the option in the tweak settings, you can try and check it the original size of the video in the gallery is different after enabled with Eneko , you can get two snapshots and you will see the difference clearly the ratio is a little different in the homescreen 
but it's not a big problem i can live with it and thank you anyway for the gorgeous tweak , i just was asking if there's a way to get the same size and specifically the resolution, thanx
