### ISSUE TITLE
Eneko 

### ISSUE THREAD

**Issue by zadrianrodriguez** [vyolit/Eneko#22]
**Describe the bug:*
Wallpaper only works for like five seconds after respring
**Steps to reproduce the behavior:**
Respring the iphone
**Crash log:**
Upload your log file to pastebin and paste the link here.

**System information:**
- iOS version:15
- Device:se 3rd gen
- Jailbreak:rootless Dopamine

**Comment by vyolit** [comment]
Do you happen to use Limneos' tweaks?

**Comment by vyolit** [comment]
If no response is provided until the end of the week I'm closing this issue.
