### ISSUE TITLE
Add scale/crop support 

### ISSUE THREAD

**Issue by lavavex** [vyolit/Eneko#7]
**Describe the requested feature:**
Add Scale/reframe for wallpapers (let me choose where to crop it/center it)
**System information:**
- iOS version: 15.4.1
- Device: 13 Pro Max
- Jailbreak: Dopamine

**Comment by lreboiras1810** [comment]
When I start a call the wallpaper stops.


iPhone 12 Pro iOS 15.4.1
Dopamine jb

**Comment by lavavex** [comment]
> When I start a call the wallpaper stops.
> 
> 
> iPhone 12 Pro iOS 15.4.1
> Dopamine jb 

Make a new issue, don't piggyback... also it's intended behaviour, you don't need video background going when another app has focus

**Comment by vyolit** [comment]
I don't plan on adding this.
